spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdv_prod?createDatabaseIfNotExist=true
    username: diel
    password: 12345
  sql:
    init:
      mode: always
security:
  token:
    secret: HXs0nlG0D+ctw233d2vg3WiT
    expiration: 43200000
